### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by AnandChowdhary** [denorg/denorg#1]
*Post ideas for potential utility packages for Deno here...*

**Comment by AnandChowdhary** [comment]
Basic static site generator written in Deno for docs sites (like @staart/site but simpler, not dependent on eleventy), takes `README.md` and content files from `content` directory and generates a nice documentation site in `public` dir for hosting

**Comment by AnandChowdhary** [comment]
Simple client for AWS S3 which does basic file uploading and fetching from S3, many many use cases with Deno servers for uploading and downloading images for user uploads

**Comment by AnandChowdhary** [comment]
Port these two projects:

- https://github.com/sindresorhus/boxen for boxed console.logs
- https://github.com/zenozeng/node-yaqrcode for QR code generation

**Comment by oplik0** [comment]
> Port these two projects:
> ...
>     * https://github.com/zenozeng/node-yaqrcode for QR code generation

Done:
https://github.com/oplik0/deno-yaqrcode

Can move it to this org if you prefer :) Though I need permission to create repositories here to do so.

**Comment by AnandChowdhary** [comment]
I'm adding you as an admin! :)

**Comment by oplik0** [comment]
A few more ideas:
* fido2/webauthn/ctap2 lib (perhaps it would be possible to create a mixed server/client lib? That is, implementing functions that are meant for browsers or maybe even client auth via cli, if that would be possible, and ones for server-side challenge generation and authentication) - I'll probably be trying to make this one soon
* [passport](http://www.passportjs.org/)-like middleware (name suggestion: dossier, since many deno modules seem to go with name starting with d :)
* Implementation of scrypt (seems like there is no scrypt lib currently :V Only bcrypt and argon2) or/and some of the hashing functions that received special recognition in PHC - perhaps doing yescrypt could be a bit better than doing scrypt since it's backwards compatible with that function. I think I'd also like to look into implementing Makwa with its delegation (securely sharing password-related computations with unsecure servers sounds fun :) and Lyra2 just because it's an interesting memory-hard algorithm (apparently even better than argon2id in that regard)

**Comment by AnandChowdhary** [comment]
> Implementation of scrypt (seems like there is no scrypt lib currently :V Only bcrypt and argon2) or/and some of the hashing functions that received special recognition in PHC - perhaps doing yescrypt could be a bit better than doing scrypt since it's backwards compatible with that function.

https://www.npmjs.com/package/scrypt has 50k+ downloads/week so this sounds like a great idea!

**Comment by yg** [comment]
This one is cool https://github.com/sindresorhus/is-docker

I started working on this!

**Comment by AnandChowdhary** [comment]
> This one is cool https://github.com/sindresorhus/is-docker

Seems simple enough, go for it! I've sent you an invitation so you can create repos in @denorg.

**Comment by AnandChowdhary** [comment]
@yg I'll add a "Getting started" guide soon, but it'd be nice if you can use the https://github.com/denorg/starter starter. See https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template.

**Comment by yg** [comment]
@AnandChowdhary Shipped :rocket: [isdocker](https://github.com/denorg/isdocker)

**Comment by yg** [comment]
Next, I'm gonna work on https://github.com/zeit/ms

WDYT?

**Comment by AnandChowdhary** [comment]
> Next, I'm gonna work on https://github.com/zeit/ms

https://deno.land/x/ms exists already :(

**Comment by yg** [comment]
Oopsy! :cry:

**Comment by yg** [comment]
@AnandChowdhary can we

- Setup **GitHub Teams** so we can discuss everything there? https://github.com/orgs/denorg/teams
- Setup **GitHub Projects** to track ideas in Kanban style? https://github.com/orgs/denorg/projects
- Update the **denorg's logo**, which looks more standard?

WDYT?

**Comment by AnandChowdhary** [comment]
Respectively:

1. Yes, great idea! I've set up the Developers team (https://github.com/orgs/denorg/teams/developers).
2. Another great idea, I've set up a shared board for discussing ideas, rather than here (https://github.com/orgs/denorg/projects/1). The only problem I have is that GitHub Projects doesn't allow commends on cards, but we still need to discuss ideas before putting them on the board, so this issue can stay open.
3. What do you think is the problem with the logo? We don't want it to look like Deno's official logo, because that may be confusing. IMHO, the @denorg logo is unique-enough to be its own separate entity, while having a non-trivial amount of resemblance with the official logo, so people know it's related. Open to thoughts here.

**Comment by AnandChowdhary** [comment]
The problem I have with the team is that the conversations we'll have are not public, but limited to the team (there seems to be no way of making them public). I'd much rather use this issue and have than public rather than use teams while not sharing them with the community.

**Comment by yg** [comment]
> 3\. What do you think is the problem with the logo? We don't want it to look like Deno's official logo, because that may be confusing. IMHO, the @denorg logo is unique-enough to be its own separate entity, while having a non-trivial amount of resemblance with the official logo, so people know it's related. Open to thoughts here.

@AnandChowdhary Adding BG color to the logo and reducing the dino size will look cool!

**Comment by yg** [comment]
@AnandChowdhary Instead of Ideas issue (this issue) we can have an ideas repo where all individual ideas can be created as an issue and if the idea is ok we can add it to the project from issue itself.

**Current Problem**

I think all ideas in a single issue can't be managed easily, it will have a long thread which is difficult to read.

**PS:** If we have more than 2000 ideas, GitHub limited it issue comments to 2000!

**Comment by AnandChowdhary** [comment]
> Instead of Ideas issue (this issue) we can have an ideas repo where all individual ideas can be created as an issue and if the idea is ok we can add it to the project from issue itself.

Good idea. We'll use this repo (denorg/denorg) for the same. I'm closing this issue. We can post new ideas as new issues and discuss them there.
